
// Autogenerated (by vm genh) - DO NOT EDIT

enum Instruction {
  LoadI = 1,
  AddI,
  SubI,
  MulI,
  DivI,
  ModI,
  ShiftI,
  AndI,
  JNZ,
  JNEG,
  JPOS,
  JumpR,
  LoadR,
  AddR,
  SubR,
  MulR,
  DivR,
  StoreR,
  IncrR,
  Call,
  Return,
  Push,
  Pop,
  LoadS,
  StoreS,
  AddS,
  SubS,
  MulS,
  DivS,
  IncrS,
  StoreSB,
  Sys,
  SysS,
};

enum Syscall {
  Exit = 1,
  Sleep,
  Write,
};
