
// Autogenerated (by vm genh)- do not edit
enum Instruction {
  LoadI = 1,
  AddI,
  SubI,
  MulI,
  DivI,
  ModI,
  ShiftI,
  AndI,
  JNZ,
  JNEG,
  JPOS,
  JumpR,
  LoadR,
  AddR,
  SubR,
  MulR,
  DivR,
  StoreR,
  IncrR,
  Sys,
};

enum Syscall {
  Exit = 1,
  Sleep,
  Write,
};
