package asm

import (
	"fmt"

	"grol.io/vm/cpu"
)

func GenHeader() int {
	fmt.Printf(`
// Autogenerated (by vm genh)- do not edit
enum Instruction {
`)
	extra := " = 1"
	for i := cpu.InvalidInstruction + 1; i < cpu.LastInstruction; i++ {
		fmt.Printf("  %v%s,\n", i, extra)
		extra = ""
	}
	fmt.Printf("};\n\nenum Syscall {\n")
	extra = " = 1"
	for i := cpu.InvalidSyscall + 1; i < cpu.LastSyscall; i++ {
		fmt.Printf("  %v%s,\n", i, extra)
		extra = ""
	}
	fmt.Printf("};\n")
	return 0
}
