// Code generated by "stringer -type=Instruction"; DO NOT EDIT.

package cpu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExitI-0]
	_ = x[LoadI-1]
	_ = x[AddI-2]
	_ = x[JNZ-3]
	_ = x[Load-4]
	_ = x[Add-5]
	_ = x[Store-6]
	_ = x[lastInstruction-7]
}

const _Instruction_name = "ExitILoadIAddIJNZLoadAddStorelastInstruction"

var _Instruction_index = [...]uint8{0, 5, 10, 14, 17, 21, 24, 29, 44}

func (i Instruction) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Instruction_index)-1 {
		return "Instruction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Instruction_name[_Instruction_index[idx]:_Instruction_index[idx+1]]
}
