// Code generated by "stringer -type=Instruction"; DO NOT EDIT.

package cpu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidInstruction-0]
	_ = x[LoadI-1]
	_ = x[AddI-2]
	_ = x[SubI-3]
	_ = x[MulI-4]
	_ = x[DivI-5]
	_ = x[ModI-6]
	_ = x[ShiftI-7]
	_ = x[AndI-8]
	_ = x[JNZ-9]
	_ = x[JNEG-10]
	_ = x[JPOS-11]
	_ = x[JumpR-12]
	_ = x[LoadR-13]
	_ = x[AddR-14]
	_ = x[SubR-15]
	_ = x[MulR-16]
	_ = x[DivR-17]
	_ = x[StoreR-18]
	_ = x[IncrR-19]
	_ = x[Call-20]
	_ = x[Ret-21]
	_ = x[Push-22]
	_ = x[Pop-23]
	_ = x[Sys-24]
	_ = x[LoadS-25]
	_ = x[StoreS-26]
	_ = x[AddS-27]
	_ = x[SubS-28]
	_ = x[MulS-29]
	_ = x[DivS-30]
	_ = x[IncrS-31]
	_ = x[StoreSB-32]
	_ = x[SysS-33]
	_ = x[LastInstruction-34]
}

const _Instruction_name = "InvalidInstructionLoadIAddISubIMulIDivIModIShiftIAndIJNZJNEGJPOSJumpRLoadRAddRSubRMulRDivRStoreRIncrRCallRetPushPopSysLoadSStoreSAddSSubSMulSDivSIncrSStoreSBSysSLastInstruction"

var _Instruction_index = [...]uint8{0, 18, 23, 27, 31, 35, 39, 43, 49, 53, 56, 60, 64, 69, 74, 78, 82, 86, 90, 96, 101, 105, 108, 112, 115, 118, 123, 129, 133, 137, 141, 145, 150, 157, 161, 176}

func (i Instruction) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Instruction_index)-1 {
		return "Instruction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Instruction_name[_Instruction_index[idx]:_Instruction_index[idx+1]]
}
