// Code generated by "stringer -type=Syscall"; DO NOT EDIT.

package cpu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[invalid-0]
	_ = x[Exit-1]
	_ = x[Print-2]
	_ = x[Read-3]
	_ = x[lastSyscall-4]
}

const _Syscall_name = "invalidExitPrintReadlastSyscall"

var _Syscall_index = [...]uint8{0, 7, 11, 16, 20, 31}

func (i Syscall) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Syscall_index)-1 {
		return "Syscall(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Syscall_name[_Syscall_index[idx]:_Syscall_index[idx+1]]
}
